- simulation1:
    consensus_name: Fruitchain
    miners:
      honest:
        mining_power: 51
      selfish:
        - mining_power: 49
        # - mining_power: 20
    gamma: 1.0
    simulation_mining_rounds: 50000
    fruit_mine_prob: 0.9
    superblock_prob: 0.1
